### PR TITLE
Sanity test update

### PR DESCRIPTION
**Pull request by GunaKKIBM**

### CODE REVIEW

**Review by ambiknai — COMMENTED** [review]
@GunaKKIBM  Could you pls add sanity execution results

**Comment by skorati** [comment]
:thumbsup: Coverage increased from [%] to [67.0125%]

**Review by sameshai — APPROVED** [review]

**Comment by GunaKKIBM** [comment]
[sanity-results.txt](https://github.com/IBM/ibm-vpc-file-csi-driver/files/13187002/sanity-results.txt)
Currently, there is no fake for Mounter, hence Volume expansion test case is failing for sanity, will fix the same in a different PR.

**Comment by skorati** [comment]
:thumbsup: Coverage increased from [%] to [67.1125%]

**Review by ambiknai — APPROVED** [review]

**Review by sameshai — APPROVED** [review]

**Pull request merged**
